# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2349364878bf22f0cf1d20702a5f2e530f6704155ef7197e595ebf30f86eecfdac892f15a6520215ebe415a2087e67033403d1d4931af134e7a69e17ad52bec

test:
  secret_key_base: ce25aec8f5193971098eddd425c6aab1b2465f95f727f9812ecabf28656cf9e801a9113529850b8a56565fbb447300d19dd899d8be2fce6f8b4db929e2f3d162

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
